global:
  scrape_interval: 5s # Fréquence de lecture des données

scrape_configs:
  - job_name: 'backend-collector'
    static_configs:
      - targets: ['host.docker.internal:3000'] # Adresse de ton Node.js